### ISSUE TITLE
twitter profile pictures disappear

### ISSUE THREAD

**Issue by pseudozach** [pseudozach/nostr.directory#11]
Note sure if it's because people change them or maybe twitter deletes them after a while but some people are saying their profile picture is not showing: https://nostr.directory/p/npub18ams6ewn5aj2n3wt2qawzglx9mr4nzksxhvrdc4gzrecw7n5tvjqctp424

not sure if we should show twitter pfp or nostr pfp or both.

**Comment by derekross** [comment]
This actually makes sense now that I think about it. Twitter probably purged my old picture. I had a picture for Christmas and changed it over the holiday was over.

**Comment by pseudozach** [comment]
should be resolved now https://github.com/pseudozach/nostr.directory/commit/c4e99c52d34d2c39e8d1832778566943f1efbccc
