### ISSUE TITLE
In the process of verifying nostr, the account was submitted normally, but it could not be passed

### ISSUE THREAD

**Issue by zerokongz** [pseudozach/nostr.directory#12]
The following is the code through the account
{
  "id": "8bde740f5ab91a9c0b3216d57ea2e34be2f1fa837bc566cc11fb611087c0a40a",
  "pubkey": "a8d9b196f14283e91033f03bef335d068fb24e069ab2c04aae7aff6621a6f974",
  "created_at": 1673028727,
  "kind": 1,
  "tags": [
    [
      "p",
      "5e7ae588d7d11eac4c25906e6da807e68c6498f49a38e4692be5a089616ceb18"
    ]
  ],
  "content": "#[0] Verifying My Public Key for mastodon: \"https://fulda.social/@kongking\"",
  "sig": "600730fec0af33a3feead23cd404d3c67b73c5d17886170990361e351772e92d3c27e767cddd9435bced21bdcdc3a233b52a0abe8cc7a4f888177fe5c4a99a17"
}

以下是没有通过的代码
{
  "id": "421984909e85541615e81e387b31d93945c4d12d530f3b61cef196adb0dc4972",
  "pubkey": "f7821f1316f1531a8daeed8c351dd2e193f8e5844bec2ef6c05f15612dd8c281",
  "created_at": 1673035478,
  "kind": 1,
  "tags": [
    [
      "p",
      "5e7ae588d7d11eac4c25906e6da807e68c6498f49a38e4692be5a089616ceb18",
      "wss://nostr.zebedee.cloud"
    ],
    [
      "client",
      "astral"
    ]
  ],
  "content": "#[0]  Verifying My Public Key for mastodon: \"https://fulda.social/@bui55862013\"",
  "sig": "b1836f7f7d25f5180982be14105758ea1d4ccc4c5293b6e2893ae9b55a6dc7f9b94f84e7eed37dc9dd4b93a9831e841642254a0c1e3281d1a96bafa0073a441c"
}

Can you tell me where this problem is coming from?

**Comment by pseudozach** [comment]
looks like both twitter and mastodon verified, so I'm closing this issue. 

Usually issue comes from your note sent on nostr not being seen on the relay we're listening to.

Here's a funnier way to say it: https://www.nostr.guru/e/65f44e3efbcf15afdb05651e9af1ef156bbcc04405c3512be09d77c15afaf469
