### ISSUE TITLE
Recheck twitter verification

### ISSUE THREAD

**Issue by erskingardner** [pseudozach/nostr.directory#15]
I changed my keys and need to have the directory check a new twitter post for verification:

The new post showing my current key is [here](https://twitter.com/erskingardner/status/1610964080046612480?s=20&t=byH7DPmUTtrDQNNZzv09wA)

The directory still shows the original tweet URL and says I haven't verified via twitter.

**Comment by pseudozach** [comment]
@erskingardner did you verify any of the posts on nostr? previous key, current key or both?

**Comment by pseudozach** [comment]
from what I can see you haven't verified your most recent key on nostr for twitter account: `erskingardner`. 

You need to send a note on nostr with the format shown on https://nostr.directory where it says `2. Verify your pubkey on nostr`

once you do this you'll show up as verified in the search and on your profile: https://nostr.directory/p/npub1zuuajd7u3sx8xu92yav9jwxpr839cs0kc3q6t56vd5u9q033xmhsk6c2uc

**Comment by erskingardner** [comment]
I had sent a note on Nostr to verify originally here: https://astral.ninja/note1zle9e5sufp4wlgdp82p0st7ehmacwqvw79q2wd4pd5w9tw40zd5qj6we3y

I'll post another note now to check. (new note: https://astral.ninja/note15636wqc0j5zh53vw4a30h7udvjud0f6nkfzp09hl72yrdr760kpsv3n3ef)

I also noticed that on my profile page, it used to show that I was NIP-05 verified but that's now gone as well. The URL for my NIP-05 verification is https://erskingardner.xyz/.well-known/nostr.json

**Comment by pseudozach** [comment]
unfortunately the most recent one you've sent still doesn't have the p tag = nostr.directory pubkey. try again by tagging our pubkey like this: `npub1teawtzxh6y02cnp9jphxm2q8u6xxfx85nguwg6ftuksgjctvavvqnsgq5u Verifying....`

>{
  "id": "a6a3a7030f95057a458eaf62fbfb8d64b8d7a753b2441796fff288368fda7d83",
  "pubkey": "1739d937dc8c0c7370aa27585938c119e25c41f6c441a5d34c6d38503e3136ef",
  "created_at": 1673339201,
  "kind": 1,
  "tags": [],
  "content": "@5e7ae588d7d11eac4c25906e6da807e68c6498f49a38e4692be5a089616ceb18 Verifying My Public Key: \"erskingardner\"",
  "sig": "8e56a785454392afd75d8ccbd4a4f327ce54cc8a135eaba17be96ba38ee13ad64061589d2df54dcb7bc6ea2893af5aa2bc48a9bd6b3a92314b55a4cd0f4c17d1"
}

**Comment by antoninconstance** [comment]
How can we force an update of public key message on Damus and Twitter?

**Comment by pseudozach** [comment]
> How can we force an update of public key message on Damus and Twitter?

if you have a new keypair. Just tweet it and it will get saved in the DB. And then publish a new note on nostr so it will be verified. your profile will show all of your keys.

**Comment by graphixillusion** [comment]
@pseudozach i have change the verification post on twitter too, re-done the verification with the post on nostr but the db is always pointing to the previous link (wrong). Is there any way to update it?

**Comment by pseudozach** [comment]
@graphixillusion  please share tweet / note id over nostr DM for support.
Key rotation should show your latest verified key by default.

**Comment by graphixillusion** [comment]
@pseudozach ok informations sent in dm on nostr. thank you for the support
