### ISSUE TITLE
Getting error `ReferenceError: Cannot access 'Base' before initialization`

### ISSUE THREAD

**Issue by ghobs91** [pseudozach/nostr.directory#18]
I'm getting the error in the title when trying to run dev locally. 

<img width="1023" alt="Screenshot 2023-01-13 at 8 18 32 PM" src="https://user-images.githubusercontent.com/4033636/212443876-4f38e4f9-7cad-4f2f-b8df-0e41a47b367e.png">

**Comment by pseudozach** [comment]
How are you running it locally? Works fine for me with 'vercel dev'.

**Comment by ghobs91** [comment]
I get the same error using `vercel dev`, hmmmm I'll keep digging

**Comment by pseudozach** [comment]
this should be resolved with https://github.com/pseudozach/nostr.directory/commit/6b32efd409266aee46b0d6d460f22efa62803429 
please let me know if you're still having issues
