### ISSUE TITLE
Recent change broke verified accounts - related to double quotes.

### ISSUE THREAD

**Issue by cybern0id** [pseudozach/nostr.directory#2]
Checked https://www.nostr.directory/ today and accounts seem to be only verified if they left the double quotes (e.g. ``"pubkey"``) in the tweet. I verified a few days ago, removing the double quotes and it showed verified until I checked the directory today.

**Comment by pseudozach** [comment]
before today we had a column for `valid` which checked if pubkey was in fact a valid key. But yesterday we replaced that column with `verified` because pretty much all pubkeys are checked for validity and there should be almost no invalid pubkeys on the directory.

`verified` is for pubkeys that sent a kind=1 text note as instructed on the website to the nostrdirectory account on nostr like this: https://www.nostr.guru/e/0564252157d2d1df86438d0bb9d9fb44e67d8536b97e8b4101771b8f6258170d

**Comment by graphixillusion** [comment]
@pseudozach i followed all the instructions but the account is still unverified. The twitter profile link and twitter proof are correct but i posted several verification messages in nostr (using astral.ninja) and the system doesn't recognize them. I also got a NIP-05 identifier but it's not recognized too. This is the link to the profile:

https://nostr.directory/p/npub1qqswd9s7almhdxa6udm64ealmrdv08ecuuqueckuq38hdd307afq4dvflg

**Comment by pseudozach** [comment]
> @pseudozach i followed all the instructions but the account is still unverified. The twitter profile link and twitter proof are correct but i posted several verification messages in nostr (using astral.ninja) and the system doesn't recognize them. I also got a NIP-05 identifier but it's not recognized too. This is the link to the profile:
> 
> https://nostr.directory/p/npub1qqswd9s7almhdxa6udm64ealmrdv08ecuuqueckuq38hdd307afq4dvflg

I looked into this. Your note is not properly tagging the nostrdirectory pubkey. There's no "p" tag on this message.
https://www.nostr.guru/e/ea6c7a65b363bc44e64b943c5c50915becb3dbe62c22a65719ec8b358bf83daf

Please send it again and depending on which client you use, make sure you do the tagging properly.

**Comment by graphixillusion** [comment]
Ok i did it, but it doesn't work with the format on the site like this one

@5e7ae588d7d11eac4c25906e6da807e68c6498f49a38e4692be5a089616ceb18 Verifying My Public Key: "Your twitter handle here"

On astral.ninja you need to type @ followed by the public key in the npub format. Like this the post will set correctly the p tag and it will works
