### ISSUE TITLE
Client-side exception when loading user profile

### ISSUE THREAD

**Issue by Bayernatoor** [pseudozach/nostr.directory#9]
When visiting a user profile I get the following exception:

`Application error: a client-side exception has occurred (see the browser console for more information).`

Console log: Seems like some sort of TypeError when relay list loads. 

![image](https://user-images.githubusercontent.com/55212954/210181306-2e489e97-f2eb-4853-a6a2-100ad2f00919.png)

Was happening every time I accessed this profile:
https://nostr.directory/p/npub1qny3tkh0acurzla8x3zy4nhrjz5zd8l9sy9jys09umwng00manysew95gx

Doesn't happen consistently anymore (or takes a few seconds)  nor could I reproduce on any other user profile.

**Comment by pseudozach** [comment]
this is due to nostr-tools encode length set to 1000. opened: https://github.com/nbd-wtf/nostr-tools/issues/74

**Comment by Bayernatoor** [comment]
@pseudozach PR to increase limit got merged, that should fix the above. https://github.com/nbd-wtf/nostr-tools/pull/76
